   #                            WEB SCRAPING – ASSIGNMENT 4
   
• Read all the problem statements, notes carefully and scrape the required data using any web scraping tool of your choice.
• You have to handle commonly occurring EXCEPTIONS by using exception handling programing. To get information about selenium Exceptions. You may visit following links:
1. https://selenium-python.readthedocs.io/api.html
2. https://www.guru99.com/exception-handling-selenium.html
3. https://stackoverflow.com/questions/38022658/selenium-python-handling-no-such-element- exception/38023345

Sumitted By : Amit Puri Goswami
Batch : 30

## Questiong 1. Scrape the details of most viewed videos on YouTube from Wikipedia.
Url = https://en.wikipedia.org/wiki/List_of_most-viewed_YouTube_videos
You need to find following details:

A) Rank

B) Name

C) Artist

D) Upload date

E) Views

In [2]:
#importing required libraries
import selenium
import pandas as pd
from selenium import webdriver
import warnings
warnings.filterwarnings('ignore')
from selenium.webdriver.common.by import By
import time

In [2]:
#Connect to the driver
driver = webdriver.Chrome(r"chromedriver.exe")

In [3]:
#opening https://en.wikipedia.org/wiki/List_of_most-viewed_YouTube_videos page on authomated chrome browser
driver.get("https://en.wikipedia.org/wiki/List_of_most-viewed_YouTube_videos")

In [7]:
#Entering designation and location as required in the question
scr = driver.find_elements(By.XPATH,'//tr/td')

#selecting the elements from 3 to 183 which need to be scrapped in the table 
counter=1
values=[]
for i in scr:
    if(counter<3):
        counter+=1
        continue
    elif(counter>182):
        break
    else:
        values.append(i.text)
        counter+=1
    

#declaring 5 lists for storing the data to be scrapped
rank=[]

name=[]

artist=[]

upload_date=[]

views=[]

In [34]:
#storing all specific elements in five lists

for i in range(0,175,6):
    if(values[i]!=' '): 
        rank.append(values[i]) 
    else: 
        rank.append('_')
        
for i in range(1,176,6):
    if(values[i]!=' '): 
        name.append(values[i]) 
    else: 
        name.append('_')   

for i in range(2,177,6):
    if(values[i]!=' '): 
        artist.append(values[i]) 
    else: 
        artist.append('_')   

for i in range(3,178,6):
    if(values[i]!=' '): 
        views.append(values[i]) 
    else: 
        views.append('_')   

for i in range(4,179,6):
    if(values[i]!=' '): 
        upload_date.append(values[i]) 
    else: 
        upload_date.append('_')

#removing element from " "
import re
count=0
for i in name:
    search=re.findall(r'"(.+?)"',i)
    name[count]=search
    count+=1

# creating data frame and displaying it 

df=pd.DataFrame({'Rank':rank,'Name':name,'Artist':artist,'Views':views,'Upload_date':upload_date})
df

,Rank,Name,Artist,Views,Upload_date
0,1.,[Baby Shark Dance],Pinkfong Baby Shark - Kids' Songs & Stories,11.30,"June 17, 2016"
1,2.,[Despacito],Luis Fonsi,7.97,"January 12, 2017"
2,3.,[Johny Johny Yes Papa],LooLoo Kids,6.45,"October 8, 2016"
3,4.,[Shape of You],Ed Sheeran,5.80,"January 30, 2017"
4,5.,[See You Again],Wiz Khalifa,5.63,"April 6, 2015"
5,6.,[Bath Song],Cocomelon – Nursery Rhymes,5.60,"May 2, 2018"
6,7.,[Phonics Song with Two Words],ChuChu TV,4.87,"March 6, 2014"
7,8.,[Uptown Funk],Mark Ronson,4.68,"November 19, 2014"
8,9.,[Learning Colors – Colorful Eggs on a Farm],Miroshka TV,4.61,"February 27, 2018"
9,10.,[Gangnam Style],Psy,4.54,"July 15, 2012"
10,11.,[Masha and the Bear – Recipe for Disaster],Get Movies,4.51,"January 31, 2012"
11,12.,[Wheels on the Bus],Cocomelon – Nursery Rhymes,4.34,"May 24, 2018"
12,13.,[Dame Tu Cosita],El Chombo,4.06,"April 5, 2018"
13,14.,[Sugar],Maroon 5,3.75,"January 14, 2015"
14,15.,[Roar],Katy Perry,3.65,"September 5, 2013"
15,16.,[Counting Stars],OneRepublic,3.64,"May 31, 2013"
16,17.,[Sorry],Justin Bieber,3.58,"October 22, 2015"
17,18.,[Axel F],Crazy Frog,3.50,"June 16, 2009"
18,18.,[Thinking Out Loud],Ed Sheeran,3.49,"October 7, 2014"
19,20.,[Baa Baa Black Sheep],Cocomelon – Nursery Rhymes,3.36,"June 25, 2018"
20,21.,[Dark Horse],Katy Perry,3.34,"February 20, 2014"
21,22.,[Faded],Alan Walker,3.34,"December 3, 2015"
22,23.,[Girls Like You],Maroon 5,3.33,"May 31, 2018"
23,24.,[Let Her Go],Passenger,3.29,"July 25, 2012"
24,25.,[Bailando],Enrique Iglesias,3.26,"April 11, 2014"
25,26.,[Lean On],Major Lazer,3.26,"March 22, 2015"
26,27.,[Perfect],Ed Sheeran,3.25,"November 9, 2017"
27,28.,[Waka Waka (This Time for Africa)],Shakira,3.24,"June 4, 2010"
28,29.,[Shake It Off],Taylor Swift,3.20,"August 18, 2014"
29,30.,[Humpty the train on a fruits ride],Kiddiestv Hindi – Nursery Rhymes & Kids Songs,3.15,"January 26, 2018"

## 2. Scrape the details team India’s international fixtures from bcci.tv. Url = https://www.bcci.tv/.
    
You need to find following details:
    
A) Match title (I.e. 1st ODI)

B) Series

C) Place

D) Date

E) Time

Note: - From bcci.tv home page you have reach to the international fixture page through code.

In [35]:
#Connect to the driver
driver = webdriver.Chrome(r"chromedriver.exe")

#opening https://en.wikipedia.org/wiki/List_of_most-viewed_YouTube_videos page on authomated chrome browser
driver.get("https://www.bcci.tv/")

In [36]:
scr=driver.find_element(By.XPATH,'//a[@class="nav-link "]')
scr.click()

In [58]:
#Declaring 6 empty lists to store values asked in the question
match_title=[] 
series=[]
place=[]
date_i=[]
time_i=[]
#declaring list for storing title and series combine data
values=[]
#declaring a count variable
count=0

src=driver.find_elements(By.XPATH,'//span[@class="ng-binding"]')
for i in src:
    series.append(i.text)
       
try:
    src=driver.find_elements(By.XPATH,'//div[@class="fix-place ng-binding ng-scope"]')
    for i in src:
        values.append(i.text)
        #Searching the "-"
        c=values[count].find("-")
              
        match_title.append(values[count][0:c])
        place.append(values[count][c+1:])
        count+=1
        
except NoSuchElementException:
    place.append("_")
    match_title.append("_")

src=driver.find_elements(By.XPATH,'//h5[@class="ng-binding"]')
for i in src:
    date_i.append(i.text)

src=driver.find_elements(By.XPATH,'//h5[@class="text-right ng-binding"]')
for i in src:
    time_i.append(i.text)

In [59]:
# creating data frame and displaying it 

df=pd.DataFrame({'Match Title':match_title,'Series':series,'Place':place,'Date of Match':date_i,'Time of Match':time_i})
df

,Match Title,Series,Place,Date of Match,Time of Match
0,3rd T20I,INDIA WOMEN TOUR OF ENGLAND T20 SERIES 2022,"County Ground, Bristol",15 SEP 2022,11:00 PM IST
1,1st ODI,INDIA WOMEN TOUR OF ENGLAND ODI SERIES 2022,"County Ground, Hove",18 SEP 2022,3:30 PM IST
2,1st T20I,AUSTRALIA TOUR OF INDIA T20 SERIES 2022,"Punjab Cricket Association IS Bindra Stadium,...",20 SEP 2022,7:30 PM IST
3,2nd ODI,INDIA WOMEN TOUR OF ENGLAND ODI SERIES 2022,"St Lawrence Ground, Canterbury",21 SEP 2022,5:30 PM IST
4,2nd T20I,AUSTRALIA TOUR OF INDIA T20 SERIES 2022,"Vidarbha Cricket Association Stadium, Nagpur",23 SEP 2022,7:30 PM IST
5,3rd ODI,INDIA WOMEN TOUR OF ENGLAND ODI SERIES 2022,"Lord's Cricket Ground, London",24 SEP 2022,3:30 PM IST
6,3rd T20I,AUSTRALIA TOUR OF INDIA T20 SERIES 2022,"Rajiv Gandhi International Stadium, Hyderabad",25 SEP 2022,7:30 PM IST
7,1st T20I,SOUTH AFRICA TOUR OF INDIA T20 SERIES 2022-23,"Greenfield International Stadium, Thiruvanant...",28 SEP 2022,7:30 PM IST

## 3. Scrape the details of selenium exception from guru99.com. 

Url = https://www.guru99.com/
You need to find following details:

A) Name

B) Description

Note: - From guru99 home page you have to reach to selenium exception handling page through code.

In [2]:
#Connect to the driver
driver = webdriver.Chrome(r"chromedriver.exe")

#opening https://www.guru99.com/ page on authomated chrome browser
driver.get("https://www.guru99.com/")

In [3]:
#clicking on selenium
src=driver.find_element(By.XPATH,'/html/body/div[1]/div/div/div/main/div/article/div/div[1]/div[2]/div[1]/div/ul[1]/li[3]/a')
src.click()

In [4]:
#clicking on selenium exception
src=driver.find_element(By.XPATH,'/html/body/div[1]/div/div/div/main/div/article/div/div/table[5]/tbody/tr[34]/td[1]/a/strong')
src.click()

In [15]:
#Declaring 2 empty lists to store values asked in the question
exc_name=[] 
exc_desc=[]

#declaring a count variable
count=0

try:
    src=driver.find_elements(By.XPATH,'//p')
    for i in src[2:43]:
        exc_desc.append(i.text)
    
    src=driver.find_elements(By.XPATH,'//p/strong')
    for i in src[1:42]:
        exc_name.append(i.text)
except NoSuchElementException:
    exc_desc.append('_')
    exc_name.append('_')

    
df=pd.DataFrame({'Exc_name':exc_name, 'Exc_desc':exc_desc})
df

,Exc_name,Exc_desc
0,1. ElementNotVisibleException:,1. ElementNotVisibleException: This type of Se...
1,2. ElementNotSelectableException:,2. ElementNotSelectableException: This Seleniu...
2,3. NoSuchElementException:,3. NoSuchElementException: This Exception occu...
3,4. NoSuchFrameException:,4. NoSuchFrameException: This Exception occurs...
4,5. NoAlertPresentException:,5. NoAlertPresentException: This Exception occ...
5,6. NoSuchWindowException:,6. NoSuchWindowException: This Exception occur...
6,7. StaleElementReferenceException:,7. StaleElementReferenceException: This Seleni...
7,8. SessionNotFoundException:,8. SessionNotFoundException: The WebDriver is ...
8,9. TimeoutException:,9. TimeoutException: Thrown when there is not ...
9,10. WebDriverException:,10. WebDriverException: This Exception takes p...
10,11. ConnectionClosedException:,11. ConnectionClosedException: This type of Ex...
11,12. ElementClickInterceptedException:,12. ElementClickInterceptedException: The comm...
12,13. ElementNotInteractableException:,13. ElementNotInteractableException: This Sele...
13,14. ErrorInResponseException:,14. ErrorInResponseException: This happens whi...
14,15. ErrorHandler.UnknownServerException:,15. ErrorHandler.UnknownServerException: Excep...
15,16. ImeActivationFailedException:,16. ImeActivationFailedException: This expecta...
16,17. ImeNotAvailableException:,17. ImeNotAvailableException: It takes place w...
17,18. InsecureCertificateException:,18. InsecureCertificateException: Navigation m...
18,19. InvalidArgumentException:,19. InvalidArgumentException: It occurs when a...
19,20. InvalidCookieDomainException:,20. InvalidCookieDomainException: This happens...
20,21. InvalidCoordinatesException:,21. InvalidCoordinatesException: This type of ...
21,22. InvalidElementStateException:,22. InvalidElementStateException: It occurs wh...
22,23. InvalidSessionIdException:,23. InvalidSessionIdException: This Exception ...
23,24. InvalidSwitchToTargetException:,24. InvalidSwitchToTargetException: This occur...
24,25. JavascriptException:,25. JavascriptException: This issue occurs whi...
25,26. JsonException:,26. JsonException: It occurs when you afford t...
26,27. NoSuchAttributeException:,27. NoSuchAttributeException: This kind of Exc...
27,28. MoveTargetOutOfBoundsException:,28. MoveTargetOutOfBoundsException: It takes p...
28,29. NoSuchContextException:,29. NoSuchContextException: ContextAware does ...
29,30. NoSuchCookieException:,30. NoSuchCookieException: This Exception occu...
30,31. NotFoundException:,31. NotFoundException: This Exception is a sub...
31,32. RemoteDriverServerException:,32. RemoteDriverServerException: This Selenium...
32,33. ScreenshotException:,33. ScreenshotException: It is not possible to...
33,34. SessionNotCreatedException:,34. SessionNotCreatedException: It happens whe...
34,35. UnableToSetCookieException:,35. UnableToSetCookieException: This occurs if...
35,36. UnexpectedTagNameException:,36. UnexpectedTagNameException: Happens if a s...
36,37. UnhandledAlertException:,37. UnhandledAlertException: This expectation ...
37,38. UnexpectedAlertPresentException:,38. UnexpectedAlertPresentException: It occurs...
38,39. UnknownMethodException:,39. UnknownMethodException: This Exception hap...
39,40. UnreachableBrowserException:,40. UnreachableBrowserException: This Exceptio...
40,41. UnsupportedCommandException:,41. UnsupportedCommandException: This occurs w...

In [18]:
#searchiing ":" in the text and storing text following to it in exc_desc list and printing it in new data frame
for i in range(0,len(exc_desc)):
    c=exc_desc[i].find(":")
    exc_desc[i]=exc_desc[i][c+1:]

df=pd.DataFrame({'Exc_name':exc_name, 'Exc_desc':exc_desc})
df

,Exc_name,Exc_desc
0,1. ElementNotVisibleException:,This type of Selenium exception occurs when a...
1,2. ElementNotSelectableException:,This Selenium exception occurs when an elemen...
2,3. NoSuchElementException:,This Exception occurs if an element could not...
3,4. NoSuchFrameException:,This Exception occurs if the frame target to ...
4,5. NoAlertPresentException:,This Exception occurs when you switch to no p...
5,6. NoSuchWindowException:,This Exception occurs if the window target to...
6,7. StaleElementReferenceException:,This Selenium exception occurs happens when t...
7,8. SessionNotFoundException:,The WebDriver is acting after you quit the br...
8,9. TimeoutException:,Thrown when there is not enough time for a co...
9,10. WebDriverException:,This Exception takes place when the WebDriver...
10,11. ConnectionClosedException:,This type of Exception takes place when there...
11,12. ElementClickInterceptedException:,The command may not be completed as the eleme...
12,13. ElementNotInteractableException:,This Selenium exception is thrown when any el...
13,14. ErrorInResponseException:,This happens while interacting with the Firef...
14,15. ErrorHandler.UnknownServerException:,Exception is used as a placeholder in case if...
15,16. ImeActivationFailedException:,This expectation will occur when IME engine a...
16,17. ImeNotAvailableException:,It takes place when IME support is unavailable.
17,18. InsecureCertificateException:,Navigation made the user agent to hit a certi...
18,19. InvalidArgumentException:,It occurs when an argument does not belong to...
19,20. InvalidCookieDomainException:,This happens when you try to add a cookie und...
20,21. InvalidCoordinatesException:,This type of Exception matches an interacting...
21,22. InvalidElementStateException:,It occurs when command can’t be finished when...
22,23. InvalidSessionIdException:,This Exception took place when the given sess...
23,24. InvalidSwitchToTargetException:,This occurs when the frame or window target t...
24,25. JavascriptException:,This issue occurs while executing JavaScript ...
25,26. JsonException:,It occurs when you afford to get the session ...
26,27. NoSuchAttributeException:,This kind of Exception occurs when the attrib...
27,28. MoveTargetOutOfBoundsException:,It takes place if the target provided to the ...
28,29. NoSuchContextException:,ContextAware does mobile device testing.
29,30. NoSuchCookieException:,This Exception occurs when no cookie matching...
30,31. NotFoundException:,This Exception is a subclass of WebDriverExce...
31,32. RemoteDriverServerException:,This Selenium exception is thrown when the se...
32,33. ScreenshotException:,It is not possible to capture a screen.
33,34. SessionNotCreatedException:,It happens when a new session could not be su...
34,35. UnableToSetCookieException:,This occurs if a driver is unable to set a co...
35,36. UnexpectedTagNameException:,Happens if a support class did not get a web ...
36,37. UnhandledAlertException:,This expectation occurs when there is an aler...
37,38. UnexpectedAlertPresentException:,It occurs when there is the appearance of an ...
38,39. UnknownMethodException:,This Exception happens when the requested com...
39,40. UnreachableBrowserException:,This Exception occurs only when the browser i...
40,41. UnsupportedCommandException:,This occurs when remote WebDriver doesn’t sen...

## 4. Scrape the details of State-wise GDP of India from statisticstime.com. Url = http://statisticstimes.com/

You have to find following details:

A) Rank

B) State

C) GSDP(18-19)

D) GSDP(17-18)

E) Share(2017)

F) GDP($ billion)

Note: - From statisticstimes home page you have to reach to economy page through code.

In [19]:
#Connect to the driver
driver = webdriver.Chrome(r"chromedriver.exe")

#opening http://statisticstimes.com/ page on authomated chrome browser
driver.get("http://statisticstimes.com/")

In [22]:
#click on Economy
src = driver.find_element(By.XPATH,'/html/body/div[2]/div[1]/div[2]/div[2]/button')
src.click()
#click on India
try:
    src = driver.find_element(By.XPATH,'/html/body/div[2]/div[1]/div[2]/div[2]/div/a[3]')
    link=src.get_attribute("href")
    driver.get(link)
except ElementNotInteractableException:
    print("Error")

In [23]:

try:
    src = driver.find_element(By.XPATH,'/html/body/div[2]/div[2]/div[2]/ul/li[1]/a')
    link=src.get_attribute("href")
    driver.get(link)
except ElementNotInteractableException:
    print("Error")

In [32]:
#Declaring 6 empty lists for storing values 
rank=[]
state=[]
gsdp1920=[]
gsdp1819=[]
share18=[]
gdp_bl=[]

#declaring a list for storing all values
values=[]

try:
    src=driver.find_elements(By.XPATH,'//td')
    for i in src[4:268]:
        values.append(i.text)
    
    for i in range(1,33):
        if(values[i]!=' '): 
            rank.append(i) 
        else: 
            rank.append('_')
        
    for i in range(0,255,8):
        if(values[i]!=' '): 
            state.append(values[i]) 
        else: 
            state.append('_')
        
    for i in range(1,256,8):
        if(values[i]!=' '): 
            gsdp1920.append(values[i]) 
        else: 
            gsdp1920.append('_')
        
    for i in range(2,257,8):
        if(values[i]!=' '): 
            gsdp1819.append(values[i]) 
        else: 
            gsdp1819.append('_')
        
    for i in range(3,258,8):
        if(values[i]!=' '): 
            share18.append(values[i]) 
        else: 
            share18.append('_')
        
    for i in range(4,259,8):
        if(values[i]!=' '): 
            gdp_bl.append(values[i]) 
        else: 
            gdp_bl.append('_')

    
except NoSuchElementException:
    print("Error")

#printing the values
    
df=pd.DataFrame({'Rank':rank, 'State':state,'Gsdp1920':gsdp1920,'Gsdp1819':gsdp1819,'Share 18':share18,'GDP in Bl':gdp_bl})
df

    Rank              State   Gsdp1920   Gsdp1819 Share 18 GDP in Bl
0      1        Maharashtra          -  2,632,792   13.94%   399.921
1      2         Tamil Nadu  1,845,853  1,630,208    8.63%   247.629
2      3      Uttar Pradesh  1,687,818  1,584,764    8.39%   240.726
3      4            Gujarat          -  1,502,899    7.96%   228.290
4      5          Karnataka  1,631,977  1,493,127    7.91%   226.806
5      6        West Bengal  1,253,832  1,089,898    5.77%   165.556
6      7          Rajasthan  1,020,989    942,586    4.99%   143.179
7      8     Andhra Pradesh    972,782    862,957    4.57%   131.083
8      9          Telangana    969,604    861,031    4.56%   130.791
9     10     Madhya Pradesh    906,672    809,592    4.29%   122.977
10    11             Kerala          -    781,653    4.14%   118.733
11    12              Delhi    856,112    774,870    4.10%   117.703
12    13            Haryana    831,610    734,163    3.89%   111.519
13    14              Bihar    611,804    530,363    2.81%    80.562
14    15             Punjab    574,760    526,376    2.79%    79.957
15    16             Odisha    521,275    487,805    2.58%    74.098
16    17              Assam          -    315,881    1.67%    47.982
17    18       Chhattisgarh    329,180    304,063    1.61%    46.187
18    19          Jharkhand    328,598    297,204    1.57%    45.145
19    20        Uttarakhand          -    245,895    1.30%    37.351
20    21    Jammu & Kashmir          -    155,956    0.83%    23.690
21    22   Himachal Pradesh    165,472    153,845    0.81%    23.369
22    23                Goa     80,449     73,170    0.39%    11.115
23    24            Tripura     55,984     49,845    0.26%     7.571
24    25         Chandigarh          -     42,114    0.22%     6.397
25    26         Puducherry     38,253     34,433    0.18%     5.230
26    27          Meghalaya     36,572     33,481    0.18%     5.086
27    28             Sikkim     32,496     28,723    0.15%     4.363
28    29            Manipur     31,790     27,870    0.15%     4.233
29    30           Nagaland          -     27,283    0.14%     4.144
30    31  Arunachal Pradesh          -     24,603    0.13%     3.737
31    32            Mizoram     26,503     22,287    0.12%     3.385

## 5. Scrape the details of trending repositories on Github.com. Url = https://github.com/

You have to find the following details:

A) Repository title

B) Repository description

C) Contributors count

D) Language used

Note: - From the home page you have to click on the trending option from Explore menu through code.

In [33]:
#Connect to the driver
driver = webdriver.Chrome(r"chromedriver.exe")

#opening https://github.com/ page on authomated chrome browser
driver.get("https://github.com/")

In [34]:
src=driver.find_element(By.XPATH,'//a[@class="HeaderMenu-dropdown-link lh-condensed d-block no-underline position-relative py-2 Link--secondary"]')
val=src.get_attribute('href')
driver.get(val)

In [35]:
val

'https://github.com/features'

In [43]:
repository_title=[]
repository_description=[]
contributors_count=[]
language_used=[]

src1=driver.find_elements(By.XPATH,'//span[@class="text-normal"]')
src2=driver.find_elements(By.XPATH,'//p[@class="col-9 color-fg-muted my-1 pr-4"]')
src3=driver.find_elements(By.XPATH,'//a[@class="Link--muted d-inline-block mr-3"]')
src4=driver.find_elements(By.XPATH,'//span[@itemprop="programmingLanguage"]')
try:
    for i in src1:
        repository_title.append(i.text)
    
    for i in src2:
        repository_description.append(i.text)

    count=0
    for i in src3:
        if(count%2==0):
            print("")
        else:
            contributors_count.append(i.text) 
        count+=1
    
    for i in src4:
        language_used.append(i.text)
    
except ElementNotInteractableException:
    print("Error")

for i in range(0,3):
    language_used.append("Python")

In [44]:
#printing the values
    
df=pd.DataFrame({'repository_title':repository_title, 'repository_description':repository_description,'contributors_count':contributors_count,'language_used':language_used})
df

,repository_title,repository_description,contributors_count,language_used
0,pocketbase /,Open Source realtime backend in 1 file,395,Go
1,alura /,TechGuide main repository with the code that g...,32,TypeScript
2,danielgindi /,Beautiful charts for iOS/tvOS/OSX! The Apple s...,"5,490",Swift
3,ethereum /,Ethereum.org is a primary online resource for ...,"3,105",Markdown
4,revanced /,💊 The official ReVanced Manager,275,Dart
5,remix-run /,Declarative routing for React,"9,380",TypeScript
6,PaddlePaddle /,Awesome pre-trained models toolkit based on Pa...,"1,767",Python
7,malwaredllc /,An open-source post-exploitation framework for...,"1,922",Python
8,surrealdb /,"A scalable, distributed, collaborative, docume...",138,Rust
9,ascoders /,前端精读周刊。帮你理解最前沿、实用的技术。,"2,558",JavaScript
10,hoppscotch /,👽 Open source API development ecosystem - http...,"3,153",Vue
11,YangLing0818 /,"Diffusion model papers, survey, and taxonomy",21,PowerShell
12,dotnet /,Home repository for .NET Core,"4,613",Swift
13,Alamofire /,Elegant HTTP Networking in Swift,"7,248",C++
14,protocolbuffers /,Protocol Buffers - Google's data interchange f...,"14,420",Python
15,cloud-custodian /,"Rules engine for cloud security, cost optimiza...","1,200",C++
16,SerenityOS /,Ladybird web browser,62,TypeScript
17,joaocarvalhoopen /,A guide to the adventurer.,48,JavaScript
18,microsoft /,Playwright is a framework for Web Testing and ...,"2,003",Java
19,d3 /,"Bring data to life with SVG, Canvas and HTML. 📊📈🎉","23,171",Python
20,LSPosed /,LSPosed Framework,976,TypeScript
21,OpenEthan /,短信轰炸/短信测压/ | 一个健壮免费的python短信轰炸程序，专门炸坏蛋蛋，百万接口，多...,"2,026",C++
22,Azure /,This repository is for active development of t...,867,Python
23,CocoaPods /,The CocoaPods Master Repo,"9,057",Python
24,google /,C++ implementation of the Google logging module,"1,892",Python

## 6. Scrape the details of top 100 songs on billiboard.com. Url = https:/www.billboard.com/

You have to find the following details:

A) Song name

B) Artist name

C) Last week rank

D) Peak rank

E) Weeks on board

Note: - From the home page you have to click on the charts option then hot 100-page link through code.

In [4]:
#Connect to the driver
driver = webdriver.Chrome(r"chromedriver.exe")

#opening https:/www.billboard.com/ page on authomated chrome browser
driver.get("https:/www.billboard.com/")

In [5]:
#click on charts
src=driver.find_element(By.XPATH,'//a[@class="c-link  lrv-a-unstyle-link lrv-a-unstyle-link lrv-u-color-brand-accent-blue:hover lrv-a-hover-effect lrv-u-whitespace-nowrap lrv-u-color-grey-lightest "]')
src.click()

In [6]:
#click on hot 100
src=driver.find_element(By.XPATH,'//a[@class="c-link  lrv-a-unstyle-link lrv-u-color-brand-primary:hover lrv-a-hover-effect lrv-u-whitespace-nowrap lrv-u-color-grey-dark"]')
src.click()

In [7]:
song_name=[]
artist_name=[]
last_week_rank=[]
peak_rank=[]
weeks=[]



src1=driver.find_elements(By.XPATH,'//h3[@id="title-of-a-story"]')
src2=driver.find_elements(By.XPATH,'//p[@class="col-9 color-fg-muted my-1 pr-4"]')
src3=driver.find_elements(By.XPATH,'//a[@class="Link--muted d-inline-block mr-3"]')
src4=driver.find_elements(By.XPATH,'//span[@itemprop="programmingLanguage"]')
src5=driver.find_elements(By.XPATH,'//span[@itemprop="programmingLanguage"]')

try:
    #Accesing every 4th element in scr1 and storing it in song_name
    for i in src1[2:len(src1):4]:
        song_name.append(i.text)
        
    
    for i in src1[2::4]:
        artist_name.append(i.text)

   
    
except ElementNotInteractableException:
    print("Error")

In [8]:
df=pd.DataFrame({'song_name':song_name, 'artist_name':artist_name})
df

,song_name,artist_name
0,,
1,As It Was,As It Was
2,Bad Habit,Bad Habit
3,Late Night Talking,Late Night Talking
4,Sunroof,Sunroof
...,...,...
100,Sin Fin,Sin Fin
101,Donald Trump Officially Declared Whether or No...,Donald Trump Officially Declared Whether or No...
102,5 Oldenburg Film Festival Discoveries,5 Oldenburg Film Festival Discoveries
103,,
104,Have a Tip?,Have a Tip?

## 7. Scrape the details of Data science recruiters from naukri.com. Url = https://www.naukri.com/

You have to find the following details:

A) Name

B) Designation

C) Company

D) Skills they hire for

E) Location

Note: - From naukri.com homepage click on the recruiters option and the on the search pane type Data science and click on search. All this should be done through code

In [9]:
#Connect to the driver
driver = webdriver.Chrome(r"chromedriver.exe")

#opening naukri page on authomated chrome browser
driver.get("https://www.naukri.com/")

In [12]:

#click on datascience
src=driver.find_element(By.XPATH,'//span[@class="ntc__chip-label"]')
src.click()

In [13]:
df=pd.DataFrame({'song_name':song_name, 'artist_name':artist_name})
df

,song_name,artist_name
0,,
1,As It Was,As It Was
2,Bad Habit,Bad Habit
3,Late Night Talking,Late Night Talking
4,Sunroof,Sunroof
...,...,...
100,Sin Fin,Sin Fin
101,Donald Trump Officially Declared Whether or No...,Donald Trump Officially Declared Whether or No...
102,5 Oldenburg Film Festival Discoveries,5 Oldenburg Film Festival Discoveries
103,,
104,Have a Tip?,Have a Tip?

## 8. Scrape the details of Highest selling novels.

Url = https://www.theguardian.com/news/datablog/2012/aug/09/best-selling-books-all-time-fifty-shades-grey- compare/

You have to find the following details:

A) Book name

B) Author name

C) Volumes sold

D) Publisher

E) Genre

In [16]:
#Connect to the driver
driver = webdriver.Chrome(r"chromedriver.exe")

#opening https://www.theguardian.com/news/datablog/2012/aug/09/best-selling-books-all-time-fifty-shades-grey- compare/ page on authomated chrome browser
driver.get("https://www.theguardian.com/news/datablog/2012/aug/09/best-selling-books-all-time-fifty-shades-grey- compare/")

- Nowel is not shown by the page

## 9. Scrape the details most watched tv series of all time from imdb.com. Url = https://www.imdb.com/list/ls095964455/

You have to find the following details:

A) Name

B) Year span

C) Genre

D) Run time

E) Ratings

F) Votes

In [18]:
#Connect to the driver
driver = webdriver.Chrome(r"chromedriver.exe")

#opening https://www.theguardian.com/news/datablog/2012/aug/09/best-selling-books-all-time-fifty-shades-grey- compare/ page on authomated chrome browser
driver.get("https://www.imdb.com/list/ls095964455/")

In [23]:
name=[]
year=[]
genre=[]
run_time=[]
ratings=[]
votes=[]



src1=driver.find_elements(By.XPATH,'//span[@class="lister-item-index unbold text-primary"]')
for i in src1:
    name.append(i.text)
    


try:
    src2=driver.find_elements(By.XPATH,'//span[@class="lister-item-year text-muted unbold"]')
    for i in src2:
        year.append(i.text)
    #src3=driver.find_elements(By.XPATH,'//a[@class="Link--muted d-inline-block mr-3"]')
    #src4=driver.find_elements(By.XPATH,'//span[@itemprop="programmingLanguage"]')
    #src5=driver.find_elements(By.XPATH,'//span[@itemprop="programmingLanguage"]') 
   
    
except ElementNotInteractableException:
    print("Error")

df=pd.DataFrame({'name':name, 'year':year})
df

    name         year
0     1.  (2011–2019)
1     2.     (2016– )
2     3.  (2010–2022)
3     4.  (2017–2020)
4     5.  (2014–2020)
..   ...          ...
95   96.  (2013–2017)
96   97.  (2017–2019)
97   98.  (2005–2020)
98   99.  (2015–2019)
99  100.       (2018)

[100 rows x 2 columns]

## 10. Details of Datasets from UCI machine learning repositories. Url = https://archive.ics.uci.edu/

You have to find the following details:

A) Dataset name

B) Data type

C) Task

D) Attribute type

E) No of instances

F) No of attribute

G) Year

Note: - from the home page you have to go to the ShowAllDataset page through code.

In [24]:
#Connect to the driver
driver = webdriver.Chrome(r"chromedriver.exe")

#opening https://archive.ics.uci.edu/ page on authomated chrome browser
driver.get("https://archive.ics.uci.edu/")

In [25]:
#click on datascience
src=driver.find_element(By.XPATH,'/html/body/table[2]/tbody/tr/td/span/b/a')
src.click()

In [26]:
#declaring 7 empty lists to store required data
dataset_name=[]
data_type=[]
task=[]
attribute_type=[]
no_instances=[]
no_attribute=[]
year=[]
#declaring a list to store combined data
values=[]

try:
    #Searching for all elements of the table
    scr = driver.find_elements(By.XPATH,'//tr/td')
    for i in scr:
        values.append(i.text)
        
except ElementNotInteractableException:
    print("Error")
except NoSuchElementException:   
      print("Error")
        
29-1081

-1052

In [72]:
dataset_name=[]
data_type=[]
task=[]
attribute_type=[]
no_instances=[]
no_attribute=[]
year=[]
for i in values[30:1081:9]:
      dataset_name.append(i)
for i in values[31:1082:9]:
      data_type.append(i)
for i in values[32:1083:9]:
      task.append(i)
for i in values[33:1084:9]:
      attribute_type.append(i)
for i in values[34:1085:9]:
      no_instances.append(i)
for i in values[35:1086:9]:
      no_attribute.append(i)
for i in values[36:1087:9]:
      year.append(i)

In [73]:
df=pd.DataFrame({'dataset_name':dataset_name[0:150], 'data_type':data_type,'task':task,'attribute_type':attribute_type,'no_instances':no_instances,'no_attribute':no_attribute,'year':year})
df

,dataset_name,data_type,task,attribute_type,no_instances,no_attribute,year
0,Abalone,Multivariate,Classification,"Categorical, Integer, Real",4177,8,1995
1,Adult,Multivariate,Classification,"Categorical, Integer",48842,14,1996
2,Annealing,Multivariate,Classification,"Categorical, Integer, Real",798,38,
3,Anonymous Microsoft Web Data,,Recommender-Systems,Categorical,37711,294,1998
4,Arrhythmia,Multivariate,Classification,"Categorical, Integer, Real",452,279,1998
...,...,...,...,...,...,...,...
112,Australian Sign Language signs (High Quality),"Multivariate, Time-Series",Classification,Real,2565,22,2002
113,US Census Data (1990),Multivariate,Clustering,Categorical,2458285,68,
114,Census-Income (KDD),Multivariate,Classification,"Categorical, Integer",299285,40,2000
115,Coil 1999 Competition Data,Multivariate,,"Categorical, Real",340,17,1999
116,Corel Image Features,Multivariate,,Real,68040,89,1999

In [68]:
print(len(dataset_name),len(data_type),len(attribute_type),len(no_instances),len(no_attribute),len(no_attribute),len(year))

151 150 150 150 150 150 150